# Generated by Django 3.1.2 on 2020-10-17 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conteudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60, verbose_name='Titulo')),
                ('descricao', models.TextField(verbose_name='Texto')),
                ('linkYoutube', models.CharField(max_length=60, verbose_name='Link youtube')),
                ('imagem', models.FileField(upload_to='')),
                ('tamanho', models.CharField(max_length=10, verbose_name='Tamanho')),
                ('lancamento', models.CharField(max_length=5, verbose_name='Lançamento')),
                ('audio', models.CharField(max_length=50, verbose_name='Áudio')),
                ('legenda', models.CharField(max_length=1, verbose_name='Legenda')),
                ('formato', models.CharField(max_length=6, verbose_name='formato')),
                ('duracao', models.CharField(max_length=6, verbose_name='Duração')),
                ('qualidadeAudio', models.CharField(max_length=2, verbose_name='Qualidade de Áudio')),
                ('qualidadeVideo', models.CharField(max_length=2, verbose_name='Qualidade de Vídeo')),
                ('linkArquivo', models.TextField(verbose_name='Link magnético')),
                ('status', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('login', models.CharField(max_length=15, unique=True, verbose_name='Login')),
                ('senha', models.CharField(max_length=15, verbose_name='Senha')),
                ('email', models.CharField(max_length=35, verbose_name='email')),
                ('CPF', models.CharField(max_length=11, verbose_name='CPF')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='Masculino', max_length=1, verbose_name='Sexo')),
                ('superAdm', models.CharField(max_length=1)),
                ('moderador', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('descricao', models.TextField()),
                ('conteudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_joao.conteudo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_joao.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=25, verbose_name='Gênero')),
                ('conteudo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_joao.conteudo')),
            ],
        ),
    ]
